backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "categories"
    label: "الأقسام والمنتجات"
    folder: "content/categories"
    create: true
    fields:
      - {label: "عنوان القسم أو المنتج", name: "title", widget: "string"}
      - {label: "الوصف", name: "body", widget: "markdown"}
      
